### ISSUE TITLE
Pull image if it doesn't exist

### ISSUE THREAD

**Issue by ddrozdov** [dimafeng/containerized-tasks#4]

**Comment by ddrozdov** [comment]
Would you please release a new version with this improvement?

**Comment by dimafeng** [comment]
@ddrozdov sorry, I don't have access to the laptop with all publishing keys until tonight. I'll do it by tomorrow.

**Comment by dimafeng** [comment]
@ddrozdov 0.5.4 is released

**Comment by ddrozdov** [comment]
Thanks!
